version: "3"
services:
  web:
    build: .
    depends_on:
      - db
    ports:
      - 5000:5000
    environment:
      DB_HOST: db
      DB_NAME: api1
      DB_USER: 'api1-user'
      DB_PASSWORD: 'api1-password'
  db:
    image: mysql:5.7
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: 'api1'
      MYSQL_USER: 'api1-user'
      MYSQL_PASSWORD: 'api1-password'
